/*
 * This file is part of the openHiTLS project.
 *
 * openHiTLS is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *     http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef AUTH_ERRNO_H
#define AUTH_ERRNO_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    HITLS_AUTH_SUCCESS,
    HITLS_AUTH_INVALID_INPUT,
    HITLS_AUTH_INVALID_CMD,
    HITLS_AUTH_INVALID_ALG,
    HITLS_AUTH_INVALID_TOKEN_TYPE,
    HITLS_AUTH_BUFFER_NOT_ENOUGH,
    HITLS_AUTH_INVALID_CRYPTO_METHOD,
    HITLS_AUTH_INVALID_TOKEN_CHALLENGE,
    HITLS_AUTH_NO_TOKEN_CHALLENGE_TYPE,
    HITLS_AUTH_NO_TOKEN_CHALLENGE_ISSUERNAME,
    HITLS_AUTH_NO_TOKEN_CHALLENGE_REDEMPTION,
    HITLS_AUTH_NO_TOKEN_CHALLENGE_REQUEST,
    HITLS_AUTH_NO_PUBKEY_INFO,
    HITLS_AUTH_NO_PRVKEY_INFO,
    HITLS_AUTH_NO_KEYPAIR_CHECK_CALLBACK,
    HITLS_AUTH_INVALID_TOKEN_REQUEST,
    HITLS_AUTH_INVALID_TOKEN_RESPONSE,
    HITLS_AUTH_INVALID_TOKEN_INSTANCE,
    HITLS_AUTH_INVALID_TOKEN_KEYID,
    HITLS_AUTH_INVALID_TOKEN_BLINDED_MSG,
    HITLS_AUTH_INVALID_TOKEN_CHALLENGE_DIGEST,
    HITLS_AUTH_CHECK_KEYPAIR_FAILED,
    HITLS_AUTH_INVALID_FREE_PKEY_CB,
} HITLS_AUTH_ERRNO;

#ifdef __cplusplus
}
#endif

#endif // AUTH_ERRNO_H