
#ifndef E2EE_KEY_EXCH_ERR_H
#define E2EE_KEY_EXCH_ERR_H

#define E2EE_SUCCESS 0
#define E2EE_FAILED 1
#define E2EE_ERR_NVALID_ARG 2
#define E2EE_ERR_NULL_INPUT 3
#define E2EE_ERR_MALLOC 3
#define E2EE_ERR_MSG_VERSION 4
#define E2EE_ERR_MSG_TYPE 5
#define E2EE_ERR_MSG_LEN 6
#define E2EE_ERR_INVALID_MSG 6
#define E2EE_ERR_CALL 7
#define E2EE_ERR_CRYPTO 8
#define E2EE_ERR_CHECK_AEAD_TAG 9
#define E2EE_ERR_KEY_EXCH 9

#define E2EE_ERR_NO_SUITABLE_KEY 10
#define E2EE_ERR_KEM_CALLBACK 11

#endif
