# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Minitest Reusable Job

on:
  workflow_call:
    inputs:
      param1:
        description: 'mini-test build parameter'
        required: true
        type: string
      param2:
        description: 'mini-test name'
        required: true
        type: string
      param3:
        description: 'mini-test run platform'
        required: true
        type: string

jobs:
  reusable-job:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ inputs.param3 }}

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: recursive
        fetch-depth: 1

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: lscpu && cd testcode/script && bash all_mini_test.sh ${{ inputs.param1 }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openhitls-${{ inputs.param2 }}
        path: ${{ github.workspace }}/build
        retention-days: 5